"""
tests/test_simulator.py

Integration and unit tests for the development Call/AI Simulator.
Verifies the full simulation sequence, polling cursor semantics, active call discovery,
and final threat result format.
"""
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.models.call import Call, CallEvent
from app.models.threat import Threat
from app.schemas.common import RiskLevel, Source
from tests.conftest import DEVICE_A, HEADERS_A


class TestSimulatorEndpoint:

    def test_trigger_sync_simulation_completes_immediately(self, client: TestClient, db: Session):
        """Triggering simulation with delay_seconds=0 runs synchronously and returns completed."""
        resp = client.post(
            "/api/devtools/simulate",
            json={
                "call_id": "call_sim_sync_001",
                "device_id": DEVICE_A,
                "delay_seconds": 0.0,
            },
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["call_id"] == "call_sim_sync_001"
        assert data["status"] == "completed"

        # Verify call row state
        call_row = db.query(Call).filter(Call.id == "call_sim_sync_001").first()
        assert call_row is not None
        assert call_row.status == "COMPLETED"
        assert call_row.threat_id is not None

        # Verify exact 10 events created
        events = db.query(CallEvent).filter(CallEvent.call_id == "call_sim_sync_001").order_by(CallEvent.seq).all()
        assert len(events) == 10
        assert [e.seq for e in events] == list(range(1, 11))

    def test_trigger_async_simulation_starts_background_task(self, client: TestClient, db: Session):
        """Triggering simulation with delay_seconds > 0 starts a background task and returns started."""
        # Mock background task so we don't actually sleep in tests
        with patch("fastapi.BackgroundTasks.add_task") as mock_add_task:
            resp = client.post(
                "/api/devtools/simulate",
                json={
                    "call_id": "call_sim_async_001",
                    "device_id": DEVICE_A,
                    "delay_seconds": 1.0,
                },
            )
            assert resp.status_code == 200
            data = resp.json()
            assert data["call_id"] == "call_sim_async_001"
            assert data["status"] == "started"
            mock_add_task.assert_called_once()

    def test_simulated_call_lifecycle_and_sequence(self, client: TestClient, db: Session):
        """Verify the exact sequence of 10 events generated by the simulator."""
        resp = client.post(
            "/api/devtools/simulate",
            json={
                "call_id": "call_sim_seq_001",
                "device_id": DEVICE_A,
                "delay_seconds": 0.0,
            },
        )
        assert resp.status_code == 200

        # Poll the events
        events_resp = client.get("/api/calls/call_sim_seq_001/events?after_seq=0")
        assert events_resp.status_code == 200
        events = events_resp.json()["events"]
        assert len(events) == 10

        # Event 1: STATUS RINGING
        assert events[0]["seq"] == 1
        assert events[0]["type"] == "STATUS"
        assert events[0]["status"] == "RINGING"

        # Event 2: STATUS IN_PROGRESS
        assert events[1]["seq"] == 2
        assert events[1]["type"] == "STATUS"
        assert events[1]["status"] == "IN_PROGRESS"

        # Event 3: TRANSCRIPT
        assert events[2]["seq"] == 3
        assert events[2]["type"] == "TRANSCRIPT"
        assert events[2]["speaker"] == "CALLER"
        assert events[2]["text"] == "Hello, I'm calling from your bank."

        # Event 4: TRANSCRIPT
        assert events[3]["seq"] == 4
        assert events[3]["type"] == "TRANSCRIPT"
        assert events[3]["speaker"] == "CALLER"
        assert events[3]["text"] == "We've detected suspicious activity on your account."

        # Event 5: RISK_UPDATE (LOW, 20)
        assert events[4]["seq"] == 5
        assert events[4]["type"] == "RISK_UPDATE"
        assert events[4]["risk_score"] == 20
        assert events[4]["risk_level"] == "LOW"

        # Event 6: TRANSCRIPT
        assert events[5]["seq"] == 6
        assert events[5]["type"] == "TRANSCRIPT"
        assert events[5]["speaker"] == "CALLER"
        assert events[5]["text"] == "We need to verify your identity to prevent account freeze."

        # Event 7: RISK_UPDATE (MEDIUM, 45)
        assert events[6]["seq"] == 7
        assert events[6]["type"] == "RISK_UPDATE"
        assert events[6]["risk_score"] == 45
        assert events[6]["risk_level"] == "MEDIUM"

        # Event 8: TRANSCRIPT
        assert events[7]["seq"] == 8
        assert events[7]["type"] == "TRANSCRIPT"
        assert events[7]["speaker"] == "CALLER"
        assert events[7]["text"] == "Please tell me the OTP you received."

        # Event 9: ALERT (CRITICAL, 97)
        assert events[8]["seq"] == 9
        assert events[8]["type"] == "ALERT"
        assert events[8]["risk_score"] == 97
        assert events[8]["risk_level"] == "CRITICAL"
        assert "OTP" in events[8]["text"]

        # Event 10: STATUS ENDED
        assert events[9]["seq"] == 10
        assert events[9]["type"] == "STATUS"
        assert events[9]["status"] == "ENDED"

    def test_active_call_discovery_flow(self, client: TestClient, db: Session):
        """Verify active call discovery works before, during, and after call completion."""
        # 1. Initially, no active call
        active_resp = client.get("/api/calls/active")
        assert active_resp.status_code == 200
        assert active_resp.json()["call_id"] is None

        # 2. Simulate call creation manually using CallService to hold it in IN_PROGRESS state
        from app.services.call import call_service
        call_service.create_call(db, "call_temp_active")
        call_service.update_status(db, "call_temp_active", "IN_PROGRESS")
        db.commit()

        # 3. Discover active call
        active_resp = client.get("/api/calls/active")
        assert active_resp.json()["call_id"] == "call_temp_active"

        # 4. End call
        call_service.update_status(db, "call_temp_active", "COMPLETED")
        db.commit()

        # 5. Discover returns null
        active_resp = client.get("/api/calls/active")
        assert active_resp.json()["call_id"] is None

    def test_event_polling_after_seq(self, client: TestClient):
        """Verify polling behavior matches the cursor-polling contract."""
        # Sync run
        client.post(
            "/api/devtools/simulate",
            json={"call_id": "call_sim_poll_001", "device_id": DEVICE_A},
        )

        # Poll with after_seq=0
        resp = client.get("/api/calls/call_sim_poll_001/events?after_seq=0")
        data = resp.json()
        assert len(data["events"]) == 10
        assert data["events"][0]["seq"] == 1

        # Poll with after_seq=6
        resp = client.get("/api/calls/call_sim_poll_001/events?after_seq=6")
        data = resp.json()
        assert len(data["events"]) == 4
        assert [e["seq"] for e in data["events"]] == [7, 8, 9, 10]

        # Poll with after_seq=10
        resp = client.get("/api/calls/call_sim_poll_001/events?after_seq=10")
        assert len(resp.json()["events"]) == 0

    def test_final_result_compliance(self, client: TestClient, db: Session):
        """Verify the final threat result conforms to contract §1.2 for CALL."""
        call_id = "call_sim_res_001"
        client.post(
            "/api/devtools/simulate",
            json={"call_id": call_id, "device_id": DEVICE_A},
        )

        # GET /api/calls/{call_id}/result
        resp = client.get(f"/api/calls/{call_id}/result")
        assert resp.status_code == 200
        data = resp.json()

        assert data["source"] == "CALL"
        assert data["risk_score"] == 97
        assert data["risk_level"] == "CRITICAL"
        assert data["threat_type"] == "Banking Scam"
        assert set(data["indicators"]) == {"Bank impersonation", "OTP request", "Urgency"}
        assert data["recommendation"] == "Hang up immediately and call your bank's official number."
        
        # Enforce contract §1.2: CALL source analyzed_content is the call_id only
        assert data["analyzed_content"] == call_id


class TestDevtoolsEnvironmentGate:

    @patch("app.core.config.settings.APP_ENV", "production")
    def test_devtools_route_only_available_in_development(self):
        """
        Verify that when APP_ENV is not 'development', devtools router is not included.
        We reload/import the clean app with overridden settings to prove this.
        """
        import importlib
        import app.api.v1.router
        import app.main

        # Force reload router module with production APP_ENV settings
        importlib.reload(app.api.v1.router)
        
        # Verify that devtools prefix router is not in router routes
        paths = [route.path for route in app.api.v1.router.api_router.routes]
        assert not any(path.startswith("/api/devtools") for path in paths)

        # Re-import clean development mode router for subsequent tests
        importlib.reload(app.api.v1.router)
